apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: kubernetes-for-the-busy-java-developer
build:
  artifacts:
  - image: ojhughes/dns-k8s-java
    context: .
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/*
