apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dns-k8s-java
  name: dns-k8s-java
  namespace: dns-demo
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting apps.me.ohughes.k8s-dns-java/namespace"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-k8s-java
  strategy: {}
  template:
    metadata:
      labels:
        app: dns-k8s-java
    spec:
      containers:
      - image: ojhughes/dns-k8s-java
        name: dns-k8s-java
        resources: {}
status: {}
