apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: discoverable-app
  name: discoverable-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discoverable-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: discoverable-app
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        resources: {}
status: {}
