apiVersion: v1
kind: Service
metadata:
  labels:
    app: discoverable-app
  name: discoverable-app
  namespace: dns-demo
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting apps.me.ohughes.k8s-dns-java/namespace"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: discoverable-app
  type: ClusterIP
status:
  loadBalancer: {}
