apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dns-k8s-java-svc
  name: dns-k8s-java-svc
  namespace: dns-demo
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting apps.me.ohughes.k8s-dns-java/namespace"
spec:
  ports:
  - name: http
    nodePort: 30037
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: dns-k8s-java
  type: NodePort
status:
  loadBalancer: {}
