apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dns-k8s-java-svc
  name: dns-k8s-java-svc
  namespace: dns-demo
spec:
  ports:
  - name: http
    nodePort: 30037
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: dns-k8s-java
  type: NodePort
status:
  loadBalancer: {}
