apiVersion: v1
kind: Service
metadata:
  labels:
    app: discoverable-app
  name: discoverable-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: discoverable-app
  type: ClusterIP
status:
  loadBalancer: {}
